CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6)
);
CREATE TABLE servers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    owner_email VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6)
);
CREATE TABLE channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6),
    server_id BIGINT NOT NULL REFERENCES servers(id)
);
CREATE TABLE server_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    joined_at TIMESTAMP(6),
    server_id BIGINT NOT NULL REFERENCES servers(id)
);
CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(2000),
    sender_email VARCHAR(255) NOT NULL,
    sender_username VARCHAR(255) NOT NULL,
    attachment_url VARCHAR(255),
    attachment_type VARCHAR(255),
    created_at TIMESTAMP(6),
    channel_id BIGINT NOT NULL REFERENCES channels(id)
);
CREATE TABLE user_devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email VARCHAR(255) NOT NULL,
    fcm_token VARCHAR(2048) NOT NULL UNIQUE,
    device_model VARCHAR(255),
    registered_at TIMESTAMP(6),
    last_seen TIMESTAMP(6)
);
CREATE INDEX idx_messages_channel_created ON messages(channel_id, created_at);
CREATE INDEX idx_members_server_email ON server_members(server_id, user_email);
CREATE INDEX idx_devices_user_email ON user_devices(user_email);
