ALTER TABLE users ADD COLUMN google_subject VARCHAR(255) UNIQUE;
ALTER TABLE users ADD COLUMN auth_version INTEGER NOT NULL DEFAULT 0;
CREATE TABLE password_recoveries (
 email VARCHAR(255) PRIMARY KEY REFERENCES users(email), code_hash VARCHAR(255) NOT NULL,
 expires_at TIMESTAMP WITH TIME ZONE NOT NULL, sent_at TIMESTAMP WITH TIME ZONE NOT NULL,
 attempts INTEGER NOT NULL DEFAULT 0, reset_hash VARCHAR(255), consumed BOOLEAN NOT NULL DEFAULT FALSE
);
