spring.application.name=chatapp-backend
# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/chatapp
spring.datasource.username=postgres
spring.datasource.password=senha123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT
jwt.secret=chatapp_chave_secreta_minimo_32_caracteres_aqui
jwt.expiration=86400000

# Porta do servidor
server.port=8080