package com.chatapp.chatapp_backend;

import com.chatapp.chatapp_backend.entity.User;
import org.hibernate.cfg.Configuration;
import org.junit.jupiter.api.Test;
import java.sql.DriverManager;
import java.util.UUID;
import static org.assertj.core.api.Assertions.assertThat;

class AuthSchemaUpgradeTest {
    @Test
    void schemaUpdatePreservesExistingAccountsAndInitializesAuthVersion() throws Exception {
        String url = "jdbc:h2:mem:auth-upgrade-" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1";
        try (var connection = DriverManager.getConnection(url, "sa", "");
             var sql = connection.createStatement()) {
            sql.execute("CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "username VARCHAR(255) NOT NULL UNIQUE, email VARCHAR(255) NOT NULL UNIQUE, "
                + "password VARCHAR(255) NOT NULL, created_at TIMESTAMP)");
            sql.execute("INSERT INTO users (username,email,password) VALUES ('existing','existing@example.test','unchanged-hash')");
            var config = new Configuration().addAnnotatedClass(User.class)
                .setProperty("hibernate.connection.url", url)
                .setProperty("hibernate.connection.username", "sa")
                .setProperty("hibernate.connection.password", "")
                .setProperty("hibernate.hbm2ddl.auto", "update")
                .setProperty("hibernate.hbm2ddl.halt_on_error", "true");
            try (var factory = config.buildSessionFactory(); var session = factory.openSession()) {
                var user = session.createQuery("from User where email = :email", User.class)
                    .setParameter("email", "existing@example.test").getSingleResult();
                assertThat(user.getAuthVersion()).isZero();
                assertThat(user.getPassword()).isEqualTo("unchanged-hash");
                assertThat(user.getGoogleSubject()).isNull();
            }
            try (var result = sql.executeQuery("SELECT COUNT(*) FROM users")) {
                result.next();
                assertThat(result.getInt(1)).isEqualTo(1);
            }
            sql.execute("DROP ALL OBJECTS");
        }
    }
}
